system:
    default:
        yui:
            combine: true
            modules:
                up-add-userprofilingblockview-plugin:
                    requires: ['plugin', 'up-userprofiling-blockview', 'ez-pluginregistry']
                    dependencyOf:
                        - 'ezs-landingpagecreatorview'
                        - 'ezs-dynamiclandingpagecreatorview'
                        - 'ezs-dynamiclandingpageeditorview'
                    path: %userprofiling_block.public_dir%/js/plugins/up-add-userprofilingblockview-plugin.js

                up-userprofiling-blockview:
                    requires:
                        - 'ezs-blockview'
                        - 'up-userprofiling-blockconfig-formview'
                        - 'userprofilingblockview-ez-template'
                    path: %userprofiling_block.public_dir%/js/views/up-userprofiling-blockview.js

                userprofilingblockview-ez-template:
                    type: 'template'
                    path: %ezstudioui.public_dir%/templates/blocks/block.hbt

                up-userprofiling-blockconfig-formview:
                    requires:
                        - 'ezs-blockpopupformview'
                        - 'up-itemsfieldview'
                        - 'event-valuechange'
                        - 'userprofilingblockconfigformview-ez-template'
                    path: %userprofiling_block.public_dir%/js/views/up-userprofiling-blockconfig-formview.js

                userprofilingblockconfigformview-ez-template:
                    type: 'template'
                    path: %userprofiling_block.public_dir%/templates/userprofiling-blockconfig.hbt

                up-itemsfieldview:
                    requires:
                        - 'ezs-selectfieldview'
                        - 'itemsfieldview-ez-template'
                    path: %userprofiling_block.public_dir%/js/views/up-itemsfieldview.js

                itemsfieldview-ez-template:
                    type: 'template'
                    path: %userprofiling_block.public_dir%/templates/userprofiling-items.hbt
